spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    filter:
      order: 10

server:
  port: 8080

firebase:
  project-id: ${FIREBASE_PROJECT_ID}
  credentials-path: ${FIREBASE_CREDENTIALS_PATH}

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}

app:
  cors:
    allowed-origins:
      - https://eventlane.io
  email:
    from-name: ${EMAIL_FROM_NAME}
    enabled: ${EMAIL_ENABLED}

resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL}

logging:
  level:
    "[io.eventlane]": DEBUG
    "[org.springframework.data.mongodb]": DEBUG
