spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/eventlane}
  security:
    filter:
      order: 10

server:
  port: 8080

firebase:
  project-id: ${FIREBASE_PROJECT_ID:eventlane-cd9d2}
  credentials-path: ${FIREBASE_CREDENTIALS_PATH:firebase-service-account.json}

logging:
  level:
    io.eventlane: DEBUG
    org.springframework.data.mongodb: DEBUG
